package org.o7planning.generateentities;
// Generated 19 Aug, 2018 10:17:53 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Route generated by hbm2java
 */
@Entity
@Table(name = "route", catalog = "railways")
public class Route implements java.io.Serializable {

	private int id;
	private Station stationByFrom;
	private Station stationByTo;
	private int distance;

	public Route() {
	}

	public Route(int id, Station stationByFrom, Station stationByTo, int distance) {
		this.id = id;
		this.stationByFrom = stationByFrom;
		this.stationByTo = stationByTo;
		this.distance = distance;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "From", nullable = false)
	public Station getStationByFrom() {
		return this.stationByFrom;
	}

	public void setStationByFrom(Station stationByFrom) {
		this.stationByFrom = stationByFrom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "To", nullable = false)
	public Station getStationByTo() {
		return this.stationByTo;
	}

	public void setStationByTo(Station stationByTo) {
		this.stationByTo = stationByTo;
	}

	@Column(name = "Distance", nullable = false)
	public int getDistance() {
		return this.distance;
	}

	public void setDistance(int distance) {
		this.distance = distance;
	}

}
