package org.o7planning.generateentities;
// Generated 19 Aug, 2018 10:17:53 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "station", catalog = "railways")
public class Station implements java.io.Serializable {

	private String code;
	private String name;
	private Set<Route> routesForFrom = new HashSet<Route>(0);
	private Set<Train> trainsForTo = new HashSet<Train>(0);
	private Set<Route> routesForTo = new HashSet<Route>(0);
	private Set<Train> trainsForFrom = new HashSet<Train>(0);
	private Set<Stop> stops = new HashSet<Stop>(0);

	public Station() {
	}

	public Station(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public Station(String code, String name, Set<Route> routesForFrom, Set<Train> trainsForTo, Set<Route> routesForTo,
			Set<Train> trainsForFrom, Set<Stop> stops) {
		this.code = code;
		this.name = name;
		this.routesForFrom = routesForFrom;
		this.trainsForTo = trainsForTo;
		this.routesForTo = routesForTo;
		this.trainsForFrom = trainsForFrom;
		this.stops = stops;
	}

	@Id

	@Column(name = "Code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByFrom")
	public Set<Route> getRoutesForFrom() {
		return this.routesForFrom;
	}

	public void setRoutesForFrom(Set<Route> routesForFrom) {
		this.routesForFrom = routesForFrom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByTo")
	public Set<Train> getTrainsForTo() {
		return this.trainsForTo;
	}

	public void setTrainsForTo(Set<Train> trainsForTo) {
		this.trainsForTo = trainsForTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByTo")
	public Set<Route> getRoutesForTo() {
		return this.routesForTo;
	}

	public void setRoutesForTo(Set<Route> routesForTo) {
		this.routesForTo = routesForTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByFrom")
	public Set<Train> getTrainsForFrom() {
		return this.trainsForFrom;
	}

	public void setTrainsForFrom(Set<Train> trainsForFrom) {
		this.trainsForFrom = trainsForFrom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "station")
	public Set<Stop> getStops() {
		return this.stops;
	}

	public void setStops(Set<Stop> stops) {
		this.stops = stops;
	}

}
