package org.o7planning.generateentities;
// Generated 19 Aug, 2018 10:17:53 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StopId generated by hbm2java
 */
@Embeddable
public class StopId implements java.io.Serializable {

	private int trainNumber;
	private int serialNumber;

	public StopId() {
	}

	public StopId(int trainNumber, int serialNumber) {
		this.trainNumber = trainNumber;
		this.serialNumber = serialNumber;
	}

	@Column(name = "Train Number", nullable = false)
	public int getTrainNumber() {
		return this.trainNumber;
	}

	public void setTrainNumber(int trainNumber) {
		this.trainNumber = trainNumber;
	}

	@Column(name = "Serial Number", nullable = false)
	public int getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(int serialNumber) {
		this.serialNumber = serialNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StopId))
			return false;
		StopId castOther = (StopId) other;

		return (this.getTrainNumber() == castOther.getTrainNumber())
				&& (this.getSerialNumber() == castOther.getSerialNumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTrainNumber();
		result = 37 * result + this.getSerialNumber();
		return result;
	}

}
