package org.o7planning.generateentities;
// Generated 19 Aug, 2018 10:17:53 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stop generated by hbm2java
 */
@Entity
@Table(name = "stop", catalog = "railways")
public class Stop implements java.io.Serializable {

	private StopId id;
	private Station station;
	private Train train;
	private Date arrivalTime;
	private Date departureTime;

	public Stop() {
	}

	public Stop(StopId id, Station station, Date arrivalTime, Date departureTime) {
		this.id = id;
		this.station = station;
		this.arrivalTime = arrivalTime;
		this.departureTime = departureTime;
	}

	public Stop(StopId id, Station station, Train train, Date arrivalTime, Date departureTime) {
		this.id = id;
		this.station = station;
		this.train = train;
		this.arrivalTime = arrivalTime;
		this.departureTime = departureTime;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "trainNumber", column = @Column(name = "Train Number", nullable = false)),
			@AttributeOverride(name = "serialNumber", column = @Column(name = "Serial Number", nullable = false)) })
	public StopId getId() {
		return this.id;
	}

	public void setId(StopId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Station", nullable = false)
	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Train Number")
	public Train getTrain() {
		return this.train;
	}

	public void setTrain(Train train) {
		this.train = train;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Arrival Time", nullable = false, length = 8)
	public Date getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(Date arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Departure Time", nullable = false, length = 8)
	public Date getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(Date departureTime) {
		this.departureTime = departureTime;
	}

}
