package org.o7planning.generateentities;
// Generated 19 Aug, 2018 10:17:53 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Train generated by hbm2java
 */
@Entity
@Table(name = "train", catalog = "railways")
public class Train implements java.io.Serializable {

	private int number;
	private Station stationByTo;
	private Station stationByFrom;
	private String name;
	private Date departTime;
	private Date arrivalTime;
	private Set<Stop> stops = new HashSet<Stop>(0);

	public Train() {
	}

	public Train(int number, Station stationByTo, Station stationByFrom, String name, Date departTime,
			Date arrivalTime) {
		this.number = number;
		this.stationByTo = stationByTo;
		this.stationByFrom = stationByFrom;
		this.name = name;
		this.departTime = departTime;
		this.arrivalTime = arrivalTime;
	}

	public Train(int number, Station stationByTo, Station stationByFrom, String name, Date departTime, Date arrivalTime,
			Set<Stop> stops) {
		this.number = number;
		this.stationByTo = stationByTo;
		this.stationByFrom = stationByFrom;
		this.name = name;
		this.departTime = departTime;
		this.arrivalTime = arrivalTime;
		this.stops = stops;
	}

	@Id

	@Column(name = "Number", unique = true, nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "To", nullable = false)
	public Station getStationByTo() {
		return this.stationByTo;
	}

	public void setStationByTo(Station stationByTo) {
		this.stationByTo = stationByTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "From", nullable = false)
	public Station getStationByFrom() {
		return this.stationByFrom;
	}

	public void setStationByFrom(Station stationByFrom) {
		this.stationByFrom = stationByFrom;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Depart Time", nullable = false, length = 8)
	public Date getDepartTime() {
		return this.departTime;
	}

	public void setDepartTime(Date departTime) {
		this.departTime = departTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Arrival Time", nullable = false, length = 8)
	public Date getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(Date arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "train")
	public Set<Stop> getStops() {
		return this.stops;
	}

	public void setStops(Set<Stop> stops) {
		this.stops = stops;
	}

}
